export interface VirtualFile {
  id: string;
  name: string;
  path: string;
  language: string;
  content: string;
}

export interface VirtualFolder {
  id: string;
  name: string;
  path: string;
  children: (VirtualFolder | VirtualFile)[];
}

export interface BuildTimelineStep {
  id: string;
  title: string;
  status: 'pending' | 'in_progress' | 'completed';
}

export interface SimulationPhase {
  id: string;
  statusText: string;
  chatMessage?: string;
  terminalLog?: string;
  newFile?: VirtualFile;
  activeStepId?: string;
  durationMs: number;
}

export const INITIAL_TIMELINE_STEPS: BuildTimelineStep[] = [
  { id: 'requirements', title: 'Requirements Analysis', status: 'pending' },
  { id: 'architecture', title: 'Architecture & Tech Stack', status: 'pending' },
  { id: 'setup', title: 'Project Setup & Config', status: 'pending' },
  { id: 'backend', title: 'Backend & Data API', status: 'pending' },
  { id: 'frontend', title: 'Frontend & UI Components', status: 'pending' },
  { id: 'testing', title: 'Automated Testing', status: 'pending' },
];

export interface Employee {
  id: string;
  name: string;
  role: string;
  department: string;
  salary: number;
  status: 'Active' | 'On Leave' | 'Terminated';
  joinDate: string;
}

export interface LeaveRequest {
  id: string;
  employeeName: string;
  type: 'Vacation' | 'Sick Leave' | 'Parental' | 'Personal';
  startDate: string;
  endDate: string;
  days: number;
  status: 'Pending' | 'Approved' | 'Rejected';
}

export interface PayrollRun {
  id: string;
  period: string;
  totalGross: number;
  taxDeductions: number;
  netPayout: number;
  employeesProcessed: number;
  status: 'Completed' | 'Processing' | 'Draft';
}

export const mockEmployees: Employee[] = [
  { id: 'E-001', name: 'Sarah Jenkins', role: 'Staff Engineer', department: 'Engineering', salary: 145000, status: 'Active', joinDate: '2022-03-15' },
  { id: 'E-002', name: 'David Chen', role: 'Product Lead', department: 'Product', salary: 155000, status: 'Active', joinDate: '2021-08-01' },
  { id: 'E-003', name: 'Elena Rostova', role: 'HR Specialist', department: 'People Ops', salary: 98000, status: 'On Leave', joinDate: '2023-01-10' },
  { id: 'E-004', name: 'Marcus Brody', role: 'Security Architect', department: 'Cybersecurity', salary: 168000, status: 'Active', joinDate: '2020-11-20' },
];

export const mockLeaveRequests: LeaveRequest[] = [
  { id: 'LR-901', employeeName: 'Elena Rostova', type: 'Parental', startDate: '2026-08-01', endDate: '2026-08-20', days: 15, status: 'Approved' },
  { id: 'LR-902', employeeName: 'Sarah Jenkins', type: 'Vacation', startDate: '2026-08-15', endDate: '2026-08-22', days: 5, status: 'Pending' },
  { id: 'LR-903', employeeName: 'David Chen', type: 'Sick Leave', startDate: '2026-08-04', endDate: '2026-08-05', days: 2, status: 'Approved' },
];

export const mockPayroll: PayrollRun = {
  id: 'PR-2026-08',
  period: 'August 2026',
  totalGross: 566000,
  taxDeductions: 141500,
  netPayout: 424500,
  employeesProcessed: 4,
  status: 'Completed',
};

export const STARTER_PROMPTS = [
  "Build an Enterprise HR Portal with Employee Login, Leave Management, Payroll Integration, Employee Dashboard and Role Based Access Control.",
  "Build a FinTech Audit & Compliance Dashboard with Real-time AI Fraud Detection and Executive PDF Reports.",
  "Build a Multi-Tenant SaaS Billing & Analytics Platform with Stripe Integration and Usage-Based Metering.",
];

export const INITIAL_PROJECT_FILES: Record<string, VirtualFile> = {
  'package.json': {
    id: 'pkg-json',
    name: 'package.json',
    path: 'package.json',
    language: 'json',
    content: `{
  "name": "enterprise-hr-portal",
  "private": true,
  "version": "1.0.0",
  "type": "module",
  "scripts": {
    "dev": "vite",
    "build": "tsc -b && vite build",
    "lint": "eslint .",
    "preview": "vite preview"
  },
  "dependencies": {
    "react": "^19.0.0",
    "react-dom": "^19.0.0",
    "lucide-react": "^0.475.0",
    "framer-motion": "^12.0.0",
    "recharts": "^2.12.0",
    "axios": "^1.7.0"
  },
  "devDependencies": {
    "@types/react": "^19.0.0",
    "@vitejs/plugin-react": "^4.3.0",
    "typescript": "^5.6.0",
    "tailwindcss": "^4.0.0",
    "vite": "^6.0.0"
  }
}`
  },
  'README.md': {
    id: 'readme-md',
    name: 'README.md',
    path: 'README.md',
    language: 'markdown',
    content: `# Enterprise HR Portal & Executive Dashboard

Generated by **Cera AI Software Engineer** for enterprise scale workforce operations.

## Architecture
- **Frontend**: React 19, TypeScript, Tailwind CSS v4, Lucide Icons
- **Backend API**: Node.js Express REST Services with RBAC Middleware
- **State & Auth**: React Context + JWT Token Authorization
- **Analytics**: Recharts Data Visualization

## Getting Started
Run the following in the terminal:
\`\`\`bash
npm run dev
\`\`\`

Access the live portal at \`http://localhost:5173\`.
`
  },
  'vite.config.ts': {
    id: 'vite-config',
    name: 'vite.config.ts',
    path: 'vite.config.ts',
    language: 'typescript',
    content: `import { defineConfig } from 'vite';
import react from '@vitejs/plugin-react';

// https://vitejs.dev/config/
export default defineConfig({
  plugins: [react()],
  server: {
    port: 5173,
    host: true,
    strictPort: true
  }
});`
  },
  'tailwind.config.js': {
    id: 'tailwind-config',
    name: 'tailwind.config.js',
    path: 'tailwind.config.js',
    language: 'javascript',
    content: `/** @type {import('tailwindcss').Config} */
module.exports = {
  content: ["./index.html", "./src/**/*.{js,ts,jsx,tsx}"],
  theme: {
    extend: {
      colors: {
        brand: {
          50: '#f0f7ff',
          500: '#0066ff',
          900: '#0a192f',
        }
      }
    },
  },
  plugins: [],
};`
  },
  'src/App.tsx': {
    id: 'app-tsx',
    name: 'App.tsx',
    path: 'src/App.tsx',
    language: 'typescript',
    content: `import React, { useState } from 'react';
import { AuthProvider, useAuth } from './contexts/AuthContext';
import { Navbar } from './components/Navbar';
import { Sidebar } from './components/Sidebar';
import { Dashboard } from './pages/Dashboard';
import { LeaveManagement } from './pages/LeaveManagement';
import { PayrollPage } from './pages/PayrollPage';
import { Login } from './pages/Login';

function MainApp() {
  const { user } = useAuth();
  const [activeTab, setActiveTab] = useState<'dashboard' | 'leave' | 'payroll'>('dashboard');

  if (!user) {
    return <Login />;
  }

  return (
    <div className="flex h-screen bg-slate-950 text-slate-100 font-sans">
      <Sidebar activeTab={activeTab} setActiveTab={setActiveTab} />
      <div className="flex-1 flex flex-col overflow-hidden">
        <Navbar user={user} />
        <main className="flex-1 overflow-y-auto p-6 bg-slate-900/60">
          {activeTab === 'dashboard' && <Dashboard />}
          {activeTab === 'leave' && <LeaveManagement />}
          {activeTab === 'payroll' && <PayrollPage />}
        </main>
      </div>
    </div>
  );
}

export function App() {
  return (
    <AuthProvider>
      <MainApp />
    </AuthProvider>
  );
}

export default App;`
  },
  'src/main.tsx': {
    id: 'main-tsx',
    name: 'main.tsx',
    path: 'src/main.tsx',
    language: 'typescript',
    content: `import React from 'react';
import ReactDOM from 'react-dom/client';
import App from './App';
import './index.css';

ReactDOM.createRoot(document.getElementById('root')!).render(
  <React.StrictMode>
    <App />
  </React.StrictMode>
);`
  },
  'src/contexts/AuthContext.tsx': {
    id: 'auth-ctx',
    name: 'AuthContext.tsx',
    path: 'src/contexts/AuthContext.tsx',
    language: 'typescript',
    content: `import React, { createContext, useContext, useState } from 'react';

export interface UserProfile {
  id: string;
  name: string;
  email: string;
  role: 'ADMIN' | 'HR_MANAGER' | 'EMPLOYEE';
  department: string;
  avatar: string;
}

interface AuthContextType {
  user: UserProfile | null;
  login: (role: 'ADMIN' | 'HR_MANAGER' | 'EMPLOYEE') => void;
  logout: () => void;
}

const AuthContext = createContext<AuthContextType | undefined>(undefined);

export const AuthProvider: React.FC<{ children: React.ReactNode }> = ({ children }) => {
  const [user, setUser] = useState<UserProfile | null>({
    id: 'emp-101',
    name: 'Alex Vance',
    email: 'alex.vance@enterprise-hr.io',
    role: 'HR_MANAGER',
    department: 'People Operations',
    avatar: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=150&auto=format&fit=crop&q=80',
  });

  const login = (role: 'ADMIN' | 'HR_MANAGER' | 'EMPLOYEE') => {
    setUser({
      id: 'emp-101',
      name: 'Alex Vance',
      email: 'alex.vance@enterprise-hr.io',
      role,
      department: 'Executive Leadership',
      avatar: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=150&auto=format&fit=crop&q=80',
    });
  };

  const logout = () => setUser(null);

  return (
    <AuthContext.Provider value={{ user, login, logout }}>
      {children}
    </AuthContext.Provider>
  );
};

export const useAuth = () => {
  const ctx = useContext(AuthContext);
  if (!ctx) throw new Error('useAuth must be used within AuthProvider');
  return ctx;
};`
  },
  'src/services/api.ts': {
    id: 'api-ts',
    name: 'api.ts',
    path: 'src/services/api.ts',
    language: 'typescript',
    content: `// Enterprise HR Gateway API Integration Service

export interface Employee {
  id: string;
  name: string;
  role: string;
  department: string;
  salary: number;
  status: 'Active' | 'On Leave' | 'Terminated';
  joinDate: string;
}

export interface LeaveRequest {
  id: string;
  employeeName: string;
  type: 'Vacation' | 'Sick Leave' | 'Parental' | 'Personal';
  startDate: string;
  endDate: string;
  days: number;
  status: 'Pending' | 'Approved' | 'Rejected';
}

export interface PayrollRun {
  id: string;
  period: string;
  totalGross: number;
  taxDeductions: number;
  netPayout: number;
  employeesProcessed: number;
  status: 'Completed' | 'Processing' | 'Draft';
}

export const mockEmployees: Employee[] = [
  { id: 'E-001', name: 'Sarah Jenkins', role: 'Staff Engineer', department: 'Engineering', salary: 145000, status: 'Active', joinDate: '2022-03-15' },
  { id: 'E-002', name: 'David Chen', role: 'Product Lead', department: 'Product', salary: 155000, status: 'Active', joinDate: '2021-08-01' },
  { id: 'E-003', name: 'Elena Rostova', role: 'HR Specialist', department: 'People Ops', salary: 98000, status: 'On Leave', joinDate: '2023-01-10' },
  { id: 'E-004', name: 'Marcus Brody', role: 'Security Architect', department: 'Cybersecurity', salary: 168000, status: 'Active', joinDate: '2020-11-20' },
];

export const mockLeaveRequests: LeaveRequest[] = [
  { id: 'LR-901', employeeName: 'Elena Rostova', type: 'Parental', startDate: '2026-08-01', endDate: '2026-08-20', days: 15, status: 'Approved' },
  { id: 'LR-902', employeeName: 'Sarah Jenkins', type: 'Vacation', startDate: '2026-08-15', endDate: '2026-08-22', days: 5, status: 'Pending' },
  { id: 'LR-903', employeeName: 'David Chen', type: 'Sick Leave', startDate: '2026-08-04', endDate: '2026-08-05', days: 2, status: 'Approved' },
];

export const mockPayroll: PayrollRun = {
  id: 'PR-2026-08',
  period: 'August 2026',
  totalGross: 566000,
  taxDeductions: 141500,
  netPayout: 424500,
  employeesProcessed: 4,
  status: 'Completed',
};`
  },
  'src/pages/Dashboard.tsx': {
    id: 'dash-page',
    name: 'Dashboard.tsx',
    path: 'src/pages/Dashboard.tsx',
    language: 'typescript',
    content: `import React from 'react';
import { Users, Calendar, DollarSign, ShieldCheck, TrendingUp } from 'lucide-react';
import { mockEmployees, mockPayroll } from '../services/api';

export const Dashboard: React.FC = () => {
  return (
    <div className="space-y-6">
      {/* Top Banner */}
      <div className="bg-gradient-to-r from-pink-600/20 via-purple-600/20 to-blue-600/20 border border-pink-500/30 p-6 rounded-2xl flex items-center justify-between">
        <div>
          <h1 className="text-2xl font-bold text-white tracking-tight">Enterprise HR Command Center</h1>
          <p className="text-slate-400 text-sm mt-1">Real-time headcount, leave approvals & payroll dispatch telemetry.</p>
        </div>
        <div className="flex items-center space-x-2 bg-emerald-500/20 border border-emerald-500/40 px-3 py-1.5 rounded-full text-emerald-300 text-xs font-semibold">
          <ShieldCheck className="w-4 h-4 text-emerald-400" />
          <span>RBAC Guard: Active</span>
        </div>
      </div>

      {/* KPI Cards */}
      <div className="grid grid-cols-1 md:grid-cols-4 gap-4">
        <div className="bg-slate-900 border border-white/10 p-5 rounded-xl flex items-center justify-between">
          <div>
            <div className="text-slate-400 text-xs font-medium uppercase tracking-wider">Total Active Employees</div>
            <div className="text-3xl font-extrabold text-white mt-1">1,248</div>
            <div className="text-xs text-emerald-400 font-semibold mt-1 flex items-center">
              <TrendingUp className="w-3.5 h-3.5 mr-1" /> +4.2% this month
            </div>
          </div>
          <div className="w-12 h-12 rounded-xl bg-blue-500/20 border border-blue-500/30 flex items-center justify-center text-blue-400">
            <Users className="w-6 h-6" />
          </div>
        </div>

        <div className="bg-slate-900 border border-white/10 p-5 rounded-xl flex items-center justify-between">
          <div>
            <div className="text-slate-400 text-xs font-medium uppercase tracking-wider">Pending Leave Requests</div>
            <div className="text-3xl font-extrabold text-amber-400 mt-1">12</div>
            <div className="text-xs text-slate-400 font-medium mt-1">Requires HR Manager Approval</div>
          </div>
          <div className="w-12 h-12 rounded-xl bg-amber-500/20 border border-amber-500/30 flex items-center justify-center text-amber-400">
            <Calendar className="w-6 h-6" />
          </div>
        </div>

        <div className="bg-slate-900 border border-white/10 p-5 rounded-xl flex items-center justify-between">
          <div>
            <div className="text-slate-400 text-xs font-medium uppercase tracking-wider">Monthly Payroll Dispatch</div>
            <div className="text-3xl font-extrabold text-emerald-400 mt-1">$424,500</div>
            <div className="text-xs text-emerald-400 font-semibold mt-1">Period: August 2026</div>
          </div>
          <div className="w-12 h-12 rounded-xl bg-emerald-500/20 border border-emerald-500/30 flex items-center justify-center text-emerald-400">
            <DollarSign className="w-6 h-6" />
          </div>
        </div>

        <div className="bg-slate-900 border border-white/10 p-5 rounded-xl flex items-center justify-between">
          <div>
            <div className="text-slate-400 text-xs font-medium uppercase tracking-wider">System Compliance</div>
            <div className="text-3xl font-extrabold text-purple-400 mt-1">100%</div>
            <div className="text-xs text-purple-300 font-medium mt-1">SOC-2 & GDPR Verified</div>
          </div>
          <div className="w-12 h-12 rounded-xl bg-purple-500/20 border border-purple-500/30 flex items-center justify-center text-purple-400">
            <ShieldCheck className="w-6 h-6" />
          </div>
        </div>
      </div>

      {/* Roster Table */}
      <div className="bg-slate-900 border border-white/10 rounded-2xl p-6">
        <h2 className="text-lg font-bold text-white mb-4">Key Personnel Directory</h2>
        <div className="overflow-x-auto">
          <table className="w-full text-left text-sm text-slate-300">
            <thead className="text-xs uppercase bg-slate-800/80 text-slate-400 border-b border-white/10">
              <tr>
                <th className="py-3 px-4">Employee ID</th>
                <th className="py-3 px-4">Name</th>
                <th className="py-3 px-4">Role</th>
                <th className="py-3 px-4">Department</th>
                <th className="py-3 px-4">Salary (USD)</th>
                <th className="py-3 px-4">Status</th>
              </tr>
            </thead>
            <tbody className="divide-y divide-white/5">
              {mockEmployees.map((emp) => (
                <tr key={emp.id} className="hover:bg-white/5">
                  <td className="py-3 px-4 font-mono text-slate-400 text-xs">{emp.id}</td>
                  <td className="py-3 px-4 font-semibold text-white">{emp.name}</td>
                  <td className="py-3 px-4">{emp.role}</td>
                  <td className="py-3 px-4">{emp.department}</td>
                  <td className="py-3 px-4 font-mono">\${emp.salary.toLocaleString()}</td>
                  <td className="py-3 px-4">
                    <span className={\`px-2.5 py-1 rounded-full text-xs font-bold \${
                      emp.status === 'Active' ? 'bg-emerald-500/20 text-emerald-400 border border-emerald-500/30' : 'bg-amber-500/20 text-amber-400 border border-amber-500/30'
                    }\`}>
                      {emp.status}
                    </span>
                  </td>
                </tr>
              ))}
            </tbody>
          </table>
        </div>
      </div>
    </div>
  );
};`
  },
  'src/pages/LeaveManagement.tsx': {
    id: 'leave-page',
    name: 'LeaveManagement.tsx',
    path: 'src/pages/LeaveManagement.tsx',
    language: 'typescript',
    content: `import React, { useState } from 'react';
import { Calendar, CheckCircle, XCircle, Plus } from 'lucide-react';
import { mockLeaveRequests, LeaveRequest } from '../services/api';

export const LeaveManagement: React.FC = () => {
  const [requests, setRequests] = useState<LeaveRequest[]>(mockLeaveRequests);

  const handleApprove = (id: string) => {
    setRequests(prev => prev.map(r => r.id === id ? { ...r, status: 'Approved' } : r));
  };

  const handleReject = (id: string) => {
    setRequests(prev => prev.map(r => r.id === id ? { ...r, status: 'Rejected' } : r));
  };

  return (
    <div className="space-y-6">
      <div className="flex items-center justify-between">
        <div>
          <h1 className="text-2xl font-bold text-white tracking-tight">Leave & Attendance Management</h1>
          <p className="text-slate-400 text-sm mt-1">Review PTO, parental leave, and automated quota deductions.</p>
        </div>
        <button className="bg-pink-600 hover:bg-pink-500 text-white font-semibold text-xs px-4 py-2 rounded-xl flex items-center space-x-2 transition-all cursor-pointer">
          <Plus className="w-4 h-4" />
          <span>New Leave Request</span>
        </button>
      </div>

      <div className="grid grid-cols-1 gap-4">
        {requests.map((req) => (
          <div key={req.id} className="bg-slate-900 border border-white/10 p-5 rounded-2xl flex items-center justify-between">
            <div className="flex items-center space-x-4">
              <div className="w-12 h-12 rounded-xl bg-purple-500/20 border border-purple-500/30 flex items-center justify-center text-purple-400">
                <Calendar className="w-6 h-6" />
              </div>
              <div>
                <div className="flex items-center space-x-3">
                  <span className="font-bold text-white text-base">{req.employeeName}</span>
                  <span className="bg-slate-800 text-slate-300 text-xs px-2.5 py-0.5 rounded-full border border-white/10">{req.type}</span>
                </div>
                <div className="text-slate-400 text-xs mt-1">
                  Dates: {req.startDate} to {req.endDate} ({req.days} working days)
                </div>
              </div>
            </div>

            <div className="flex items-center space-x-3">
              {req.status === 'Pending' ? (
                <>
                  <button onClick={() => handleApprove(req.id)} className="bg-emerald-600/20 hover:bg-emerald-600/30 text-emerald-300 border border-emerald-500/40 px-3 py-1.5 rounded-xl text-xs font-bold flex items-center space-x-1.5 transition-all cursor-pointer">
                    <CheckCircle className="w-4 h-4 text-emerald-400" />
                    <span>Approve</span>
                  </button>
                  <button onClick={() => handleReject(req.id)} className="bg-red-600/20 hover:bg-red-600/30 text-red-300 border border-red-500/40 px-3 py-1.5 rounded-xl text-xs font-bold flex items-center space-x-1.5 transition-all cursor-pointer">
                    <XCircle className="w-4 h-4 text-red-400" />
                    <span>Reject</span>
                  </button>
                </>
              ) : (
                <span className={\`px-3 py-1 rounded-full text-xs font-extrabold border \${
                  req.status === 'Approved' ? 'bg-emerald-500/20 text-emerald-400 border-emerald-500/30' : 'bg-red-500/20 text-red-400 border-red-500/30'
                }\`}>
                  {req.status}
                </span>
              )}
            </div>
          </div>
        ))}
      </div>
    </div>
  );
};`
  },
  'src/pages/PayrollPage.tsx': {
    id: 'payroll-page',
    name: 'PayrollPage.tsx',
    path: 'src/pages/PayrollPage.tsx',
    language: 'typescript',
    content: `import React from 'react';
import { CheckCircle2 } from 'lucide-react';
import { mockPayroll } from '../services/api';

export const PayrollPage: React.FC = () => {
  return (
    <div className="space-y-6">
      <div>
        <h1 className="text-2xl font-bold text-white tracking-tight">Payroll & Compensation Engine</h1>
        <p className="text-slate-400 text-sm mt-1">Direct deposit disbursements, tax withholdings, and audit logs.</p>
      </div>

      <div className="bg-slate-900 border border-white/10 rounded-2xl p-6 space-y-6">
        <div className="flex items-center justify-between border-b border-white/10 pb-4">
          <div>
            <div className="text-xs uppercase text-slate-400 font-bold tracking-wider">Active Disbursement Cycle</div>
            <div className="text-xl font-bold text-white mt-0.5">{mockPayroll.period}</div>
          </div>
          <span className="bg-emerald-500/20 border border-emerald-500/40 text-emerald-300 font-bold text-xs px-3 py-1 rounded-full flex items-center space-x-1.5">
            <CheckCircle2 className="w-4 h-4 text-emerald-400" />
            <span>Direct Deposit Dispatched</span>
          </span>
        </div>

        <div className="grid grid-cols-1 md:grid-cols-3 gap-4">
          <div className="bg-slate-950 p-4 rounded-xl border border-white/5">
            <div className="text-slate-400 text-xs font-semibold">Total Gross Payroll</div>
            <div className="text-2xl font-extrabold text-white mt-1">\${mockPayroll.totalGross.toLocaleString()}</div>
          </div>
          <div className="bg-slate-950 p-4 rounded-xl border border-white/5">
            <div className="text-slate-400 text-xs font-semibold">Statutory Tax Withholdings</div>
            <div className="text-2xl font-extrabold text-amber-400 mt-1">\${mockPayroll.taxDeductions.toLocaleString()}</div>
          </div>
          <div className="bg-slate-950 p-4 rounded-xl border border-white/5">
            <div className="text-slate-400 text-xs font-semibold">Net Employee Dispatched</div>
            <div className="text-2xl font-extrabold text-emerald-400 mt-1">\${mockPayroll.netPayout.toLocaleString()}</div>
          </div>
        </div>
      </div>
    </div>
  );
};`
  },
  'server/index.ts': {
    id: 'server-index',
    name: 'index.ts',
    path: 'server/index.ts',
    language: 'typescript',
    content: `import express from 'express';
import cors from 'cors';

const app = express();
const PORT = process.env.PORT || 4000;

app.use(cors());
app.use(express.json());

app.get('/api/health', (req, res) => {
  res.json({ status: 'OK', service: 'Enterprise HR Backend API', uptime: process.uptime() });
});

app.listen(PORT, () => {
  console.log(\`[HR-API] Express server running on port \${PORT}\`);
});`
  }
};

// Simulation timeline events (2-minute smooth progression, ~120s total)
export const SIMULATION_PHASES: SimulationPhase[] = [
  // Stage 0: Requirements Analysis
  {
    id: 'p-1',
    statusText: 'Thinking...',
    chatMessage: 'Analyzing project prompt: "Build an Enterprise HR Portal with Employee Login, Leave Management, Payroll Integration, Employee Dashboard and Role Based Access Control."',
    activeStepId: 'requirements',
    durationMs: 3000,
  },
  {
    id: 'p-2',
    statusText: 'Understanding requirements...',
    chatMessage: 'Identified core modules: Authentication & RBAC, Employee Roster, Leave Management Engine, Payroll Integration Service, and Dashboard Analytics.',
    terminalLog: '[Cera AI] Requirements parsed. Initializing module graph...',
    activeStepId: 'requirements',
    durationMs: 4000,
  },
  {
    id: 'p-3',
    statusText: 'Breaking project into modules...',
    chatMessage: 'Decomposing application architecture into modular React 19 micro-frontend views with Express API backend gateway.',
    activeStepId: 'requirements',
    durationMs: 4000,
  },

  // Stage 1: Architecture & Tech Stack
  {
    id: 'p-4',
    statusText: 'Designing application architecture...',
    chatMessage: 'Designing type-safe architecture with TypeScript, Tailwind CSS v4, and React Context state management.',
    activeStepId: 'architecture',
    durationMs: 4500,
  },
  {
    id: 'p-5',
    statusText: 'Selecting technology stack...',
    chatMessage: 'Selected Tech Stack:\n- React 19 + TypeScript\n- Tailwind CSS v4\n- Express REST API\n- Lucide Icons & Recharts',
    terminalLog: 'Selecting stack: React 19, Vite 6, TypeScript 5.6, Tailwind CSS 4',
    activeStepId: 'architecture',
    durationMs: 4000,
  },

  // Stage 2: Project Setup & Config Files
  {
    id: 'p-6',
    statusText: 'Generating folder structure...',
    terminalLog: 'Initializing project Titan (enterprise-hr-portal)...\n✔ Folder hierarchy created',
    newFile: INITIAL_PROJECT_FILES['package.json'],
    activeStepId: 'setup',
    durationMs: 5000,
  },
  {
    id: 'p-7',
    statusText: 'Creating configuration files...',
    terminalLog: 'Writing vite.config.ts, tailwind.config.js, tsconfig.json...\n✔ Config files initialized',
    newFile: INITIAL_PROJECT_FILES['vite.config.ts'],
    activeStepId: 'setup',
    durationMs: 4500,
  },
  {
    id: 'p-8',
    statusText: 'Installing dependencies...',
    chatMessage: 'Installing core runtime and dev dependencies via npm package manager...',
    terminalLog: 'Installing dependencies...\n$ npm install\n+ react@19.0.0\n+ react-dom@19.0.0\n+ lucide-react@0.475.0\n+ framer-motion@12.0.0\nadded 584 packages in 3.8s',
    newFile: INITIAL_PROJECT_FILES['README.md'],
    activeStepId: 'setup',
    durationMs: 6000,
  },

  // Stage 3: Backend & Database Schemas
  {
    id: 'p-9',
    statusText: 'Generating backend...',
    chatMessage: 'Creating RESTful API server structure and Express controllers for HR endpoints.',
    terminalLog: '[Backend Generator] Initializing server/index.ts REST endpoints...',
    newFile: INITIAL_PROJECT_FILES['server/index.ts'],
    activeStepId: 'backend',
    durationMs: 6000,
  },
  {
    id: 'p-10',
    statusText: 'Creating API endpoints...',
    chatMessage: 'Implementing /api/employees, /api/leave-requests, and /api/payroll endpoints.',
    terminalLog: '[API Service] Compiled TypeScript schemas for Employee, LeaveRequest, and PayrollRun models.',
    newFile: INITIAL_PROJECT_FILES['src/services/api.ts'],
    activeStepId: 'backend',
    durationMs: 6000,
  },

  // Stage 4: Frontend & UI Components
  {
    id: 'p-11',
    statusText: 'Generating frontend...',
    chatMessage: 'Building single page React application shell with navigation router and dynamic layout container.',
    terminalLog: 'Generating frontend components...\nWriting src/App.tsx and src/main.tsx',
    newFile: INITIAL_PROJECT_FILES['src/App.tsx'],
    activeStepId: 'frontend',
    durationMs: 6500,
  },
  {
    id: 'p-12',
    statusText: 'Connecting routes...',
    chatMessage: 'Setting up client-side tab switching for Dashboard, Leave Management, and Payroll Page.',
    terminalLog: 'Connecting routes and views...',
    newFile: INITIAL_PROJECT_FILES['src/main.tsx'],
    activeStepId: 'frontend',
    durationMs: 5000,
  },
  {
    id: 'p-13',
    statusText: 'Creating UI components...',
    chatMessage: 'Generating Executive HR Dashboard with live KPI stat widgets and headcount roster table.',
    terminalLog: '[UI Component] Generating src/pages/Dashboard.tsx...',
    newFile: INITIAL_PROJECT_FILES['src/pages/Dashboard.tsx'],
    activeStepId: 'frontend',
    durationMs: 6500,
  },
  {
    id: 'p-14',
    statusText: 'Implementing authentication...',
    chatMessage: 'Injecting AuthContext.tsx with Role Based Access Control (ADMIN, HR_MANAGER, EMPLOYEE).',
    terminalLog: '[Auth Engine] Generating src/contexts/AuthContext.tsx and RBAC security guard...',
    newFile: INITIAL_PROJECT_FILES['src/contexts/AuthContext.tsx'],
    activeStepId: 'frontend',
    durationMs: 6000,
  },
  {
    id: 'p-15',
    statusText: 'Generating reusable components...',
    chatMessage: 'Generating Leave Management module with approval workflows and PTO quota counters.',
    terminalLog: '[UI Component] Generating src/pages/LeaveManagement.tsx...',
    newFile: INITIAL_PROJECT_FILES['src/pages/LeaveManagement.tsx'],
    activeStepId: 'frontend',
    durationMs: 6000,
  },
  {
    id: 'p-16',
    statusText: 'Generating Payroll Integration module...',
    chatMessage: 'Generating Payroll & Compensation view with tax withholdings calculator and disbursement status.',
    terminalLog: '[UI Component] Generating src/pages/PayrollPage.tsx...',
    newFile: INITIAL_PROJECT_FILES['src/pages/PayrollPage.tsx'],
    activeStepId: 'frontend',
    durationMs: 6000,
  },

  // Stage 5: Testing & Optimization
  {
    id: 'p-17',
    statusText: 'Optimizing project...',
    chatMessage: 'Minifying bundle, configuring tree-shaking, and verifying responsive layout CSS.',
    terminalLog: 'Compiling assets...\n✔ 24 modules compiled successfully in 1.2s',
    activeStepId: 'testing',
    durationMs: 5000,
  },
  {
    id: 'p-18',
    statusText: 'Running internal tests...',
    chatMessage: 'Executing unit test suite for Auth context, API payload serializers, and UI rendering.',
    terminalLog: 'Running test suite...\n PASS  src/contexts/AuthContext.test.ts\n PASS  src/services/api.test.ts\n PASS  src/pages/Dashboard.test.tsx\n\nTest Suites: 3 passed, 3 total\nSnapshots:   0 total\nTime:        1.42s',
    activeStepId: 'testing',
    durationMs: 5500,
  },
  {
    id: 'p-19',
    statusText: 'Preparing development environment...',
    terminalLog: 'Finalizing build artifacts...\n✔ Ready for dev server execution',
    activeStepId: 'testing',
    durationMs: 4000,
  },

  // Stage 6: Finished!
  {
    id: 'p-20',
    statusText: 'Project ready.',
    chatMessage: 'Project successfully generated.\n\n✓ Frontend\n✓ Backend\n✓ API\n✓ Authentication\n✓ Configuration\n✓ Testing Complete\n\nTo start the development server, run:\n\n```bash\nnpm run dev\n```',
    terminalLog: '\nFinished successfully.\n\nProject generated successfully.\nTo start the development server, run:\n  npm run dev\n',
    activeStepId: 'testing',
    durationMs: 1000,
  }
];
